import type { ZodType } from 'zod';
import { beforeAll, describe, expect, it } from 'vitest';

let dashboardRequestSchema: ZodType;
let emailChangeConfirmSchema: ZodType;
let phoneChangeConfirmSchema: ZodType;

beforeAll(async () => {
  process.env.AUTH_SESSION_SECRET ||= 'test-client-session-secret-with-enough-length';
  ({ emailChangeConfirmSchema, phoneChangeConfirmSchema } = await import('../../backend/src/routes/me.js'));
  ({ dashboardRequestSchema } = await import('../../backend/src/routes/dashboard.js'));
});

const validDashboardRequest = {
  caseDetails: 'A production-safe request validation test payload.',
  consultationMode: 'video',
  documentUploadIds: [],
  documents: [],
  legalDomain: 'corporate',
  pastLegalAction: false,
  preferredDate: '2026-06-15',
  preferredEndAtUtc: '2026-06-15T10:45:00.000Z',
  preferredStartAtUtc: '2026-06-15T10:00:00.000Z',
  preferredTime: '10:00-10:45',
  preferredTimezone: 'UTC',
  services: ['document-review'],
  urgency: 'standard',
};

const expectInvalid = (schema: ZodType, payload: unknown, message: string) => {
  const result = schema.safeParse(payload);

  expect(result.success).toBe(false);
  if (!result.success) {
    expect(result.error.issues.map((issue) => issue.message)).toContain(message);
  }
};

describe('client verification code validation', () => {
  it('accepts 6-digit email and phone change codes', () => {
    expect(emailChangeConfirmSchema.safeParse({ code: '123456', email: 'client@example.com' }).success).toBe(true);
    expect(phoneChangeConfirmSchema.safeParse({ code: '654321', phone: '+15551234567' }).success).toBe(true);
  });

  it('rejects alphabetic, short, and long email change codes', () => {
    for (const code of ['abcdef', '12345', '1234567']) {
      expectInvalid(
        emailChangeConfirmSchema,
        { code, email: 'client@example.com' },
        'Enter the 6-digit verification code.'
      );
    }
  });

  it('rejects alphabetic, short, and long phone change codes', () => {
    for (const code of ['abcdef', '12345', '1234567']) {
      expectInvalid(
        phoneChangeConfirmSchema,
        { code, phone: '+15551234567' },
        'Enter the 6-digit verification code.'
      );
    }
  });
});

describe('dashboard request schedule validation', () => {
  it('accepts an ISO date and generated 45-minute time window', () => {
    expect(dashboardRequestSchema.safeParse(validDashboardRequest).success).toBe(true);
  });

  it('rejects arbitrary preferred date strings', () => {
    expectInvalid(
      dashboardRequestSchema,
      { ...validDashboardRequest, preferredDate: 'June 15, 2026' },
      'Choose a valid preferred date.'
    );
  });

  it('rejects arbitrary preferred time strings', () => {
    expectInvalid(
      dashboardRequestSchema,
      { ...validDashboardRequest, preferredTime: '10:00 AM - 11:00 AM' },
      'Choose a valid preferred time window.'
    );
  });

  it('rejects time windows that are not generated by the wizard cadence', () => {
    expectInvalid(
      dashboardRequestSchema,
      { ...validDashboardRequest, preferredTime: '10:15-11:00' },
      'Choose a valid preferred time window.'
    );
  });

  it('rejects reversed UTC windows when UTC snapshots are submitted', () => {
    expectInvalid(
      dashboardRequestSchema,
      {
        ...validDashboardRequest,
        preferredEndAtUtc: '2026-06-15T10:00:00.000Z',
        preferredStartAtUtc: '2026-06-15T10:45:00.000Z',
      },
      'Choose a valid preferred time window.'
    );
  });
});
